# Generated by Django 4.2.1 on 2023-05-13 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 7, 29, 11, 621965, tzinfo=datetime.timezone.utc)),
        ),
    ]
