# Generated by Django 4.2.1 on 2023-05-13 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_website_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 7, 33, 20, 886743, tzinfo=datetime.timezone.utc)),
        ),
    ]
